In [1]:
import pandas as pd
import requests
import numpy as np

# Accessing the FPL API & Reading In the Data

In [2]:
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'
r = requests.get(url)
json = r.json()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

# Building Our 3 Dataframes (Elements, Element_Types, & Teams)

In [4]:
# uncommmenting the next line lets you see what dictionary keys are included in the json data
# json.keys()
elements_df = pd.DataFrame(json['elements'])
### This is the MAIN dataframe and includes all of the data points that we care about
elements_types_df = pd.DataFrame(json['element_types'])
### This is a SUPPORTING dataframe and will help map position and other elements to the main df
teams_df = pd.DataFrame(json['teams'])
### This is a SUPPORTING dataframe and will help map teams to the players in the main df

In [20]:
# we want to change the settings so that we can show all of the dataframes' columns
### Step 1) see how many columns each of the dataframes have (rows, columns)
elements_df.shape
### 67 columns
elements_types_df.shape
### 11 columns
teams_df.shape
### 21 columns

### Step 2) change pandas settings to display all columns (and rows just in case) for the df with the most columns
pd.set_option('display.max_columns', 67)
pd.set_option('display.max_rows', 67)

In [27]:
# Uncomment to see the top 5 rows of all 3 dataframes
# elements_df.head()
# elements_types_df.head()
# teams_df.head()

,code,draw,form,id,loss,name,played,points,position,short_name,strength,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,4,None,False,0,1190,1270,1190,1200,1160,1270,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,2,None,False,0,1050,1080,1010,1080,1000,1110,2
2,36,0,None,3,0,Brighton,0,0,0,BHA,2,None,False,0,1070,1070,1100,1130,1060,1060,131
3,90,0,None,4,0,Burnley,0,0,0,BUR,3,None,False,0,1140,1150,1130,1240,1050,1170,43
4,8,0,None,5,0,Chelsea,0,0,0,CHE,4,None,False,0,1200,1260,1140,1270,1240,1250,4

# Cleaning Up The Main Dataframe